development:
  secret_key_base: changeme

test:
  secret_key_base: changeme

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
